function subplot_param = setup_subplot_param(contourf_vis_data)
subplot_param = struct('title_vis_data', {cell(size(contourf_vis_data))}, ...
                    'caxis_data', {cell(size(contourf_vis_data))}, ...
                    'set_pbaspect', {cell(size(contourf_vis_data))}, ...
                    'ContourLineValue_data', {cell(size(contourf_vis_data))}, ... 
                    'display_globalCbar', {cell(1,1)});
end